default: true
MD013: # line-length
  code_blocks: false
  tables: false
  line_length: 100
MD033: false # inline HTML allowed (used for Redoc embed)
MD041: false # first line heading not required for partials
MD004:
  style: dash
MD007:
  indent: 2
MD025: false
