# markdownlint-cli2 Configuration
# https://github.com/DavidAnson/markdownlint-cli2

# Include all markdown files
globs:
  - "**/*.md"

# Ignore specific files/directories
ignores:
  - "node_modules"
  - ".venv"
  - "site"
  - "_site"

# markdownlint rules configuration
config:
  # MD001: Header levels should only increment by one level at a time
  MD001: true

  # MD003: Header style (consistent)
  MD003:
    style: "atx"

  # MD004: Unordered list style (consistent)
  MD004:
    style: "dash"

  # MD007: Unordered list indentation
  MD007:
    indent: 4
    start_indented: false
    start_indent: 2

  # MD009: Trailing spaces (allow 2 for line breaks)
  MD009:
    br_spaces: 2
    list_item_empty_lines: false
    strict: false

  # MD010: Hard tabs
  MD010:
    code_blocks: true
    spaces_per_tab: 4

  # MD012: Multiple consecutive blank lines
  MD012:
    maximum: 2

  # MD013: Line length (relaxed for documentation)
  MD013:
    line_length: 120
    heading_line_length: 80
    code_blocks: false
    tables: false
    headings: true
    headers: true
    strict: false
    stern: false

  # MD022: Headers should be surrounded by blank lines
  MD022:
    lines_above: 1
    lines_below: 1

  # MD024: Multiple headers with the same content
  MD024:
    allow_different_nesting: true
    siblings_only: false

  # MD025: Multiple top level headers in the same document
  MD025: false

  # MD026: Trailing punctuation in header
  MD026:
    punctuation: ".,;:!?"

  # MD029: Ordered list item prefix
  MD029:
    style: "ordered"

  # MD030: Spaces after list markers
  MD030:
    ul_single: 1
    ol_single: 1
    ul_multi: 1
    ol_multi: 1

  # MD033: Allow inline HTML (needed for MkDocs)
  MD033:
    allowed_elements:
      - "div"
      - "span"
      - "br"
      - "sub"
      - "sup"
      - "kbd"
      - "mark"
      - "details"
      - "summary"

  # MD034: Bare URL used (allow for documentation)
  MD034: false

  # MD036: Emphasis used instead of header
  MD036:
    punctuation: ".,;:!?。，；：！？"

  # MD040: Fenced code blocks should have a language specified
  MD040: true

  # MD041: First line in file should be a top level header
  MD041:
    level: 1
    front_matter_title: "^\\s*title\\s*[:=]"

  # MD046: Code block style (consistent)
  MD046:
    style: "fenced"

  # MD047: Files should end with a single newline character
  MD047: true

  # MD048: Code fence style (consistent)
  MD048:
    style: "backtick"

  # MD049: Emphasis style (consistent)
  MD049:
    style: "asterisk"

  # MD050: Strong style (consistent)
  MD050:
    style: "asterisk"
