repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^mkdocs\.yml$
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: detect-private-key
        exclude: ^docs/40-secure-mqtt/provision-payload\.md$
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        name: markdownlint (docs)
        files: '^(docs/|README.md|openapi/.*\.md)$'
        args: ["--config", ".markdownlint.yaml", "--"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies: []
        args:
          - --config=.codespellrc
          - --skip=site
          - --check-filenames
          - --check-hidden
          - --
        files: '^(docs/|README.md|openapi/|mkdocs\.yml|\.pre-commit-config\.yaml|\.yamllint|\.markdownlint\.yaml)$'

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: '^openapi/.*\.(yml|yaml)$'
        exclude: '^openapi/paths/sd-card\.yaml$'
        args: ["-c", ".yamllint"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff (lint)
        args: ["--fix"]
        additional_dependencies: []
      - id: ruff-format
        name: ruff (format)
        additional_dependencies: []

  # Optional heavy checks on pre-push to keep commits fast
  - repo: local
    hooks:
      - id: mkdocs-build
        name: mkdocs build (strict)
        entry: mkdocs build --strict --clean
        language: python
        additional_dependencies:
          - mkdocs>=1.6
          - mkdocs-material>=9.5
          - mkdocs-macros-plugin>=1.0
          - pymdown-extensions>=10.0
        pass_filenames: false
        stages: [pre-push]
      - id: prance-validate
        name: OpenAPI validate (prance)
        entry: prance validate openapi/api.yaml
        language: python
        additional_dependencies:
          - prance>=25.4.0
        pass_filenames: false
        stages: [pre-push]
